version: "3.8"
services:
  rabbit:
    image: rabbitmq:3.12-management
    hostname: rabbitmq
    container_name: rabbitmq-ms
    ports:
      - "5672:5672"
      - "15672:15672"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - wiremoney


  eurekaserver:
    image: jpelegrino/eurekaserver:1.0
    container_name: eurekaserver-ms
    ports:
      - "8071:8071"
    deploy:
      resources:
        limits:
          memory: 700m
      restart_policy:
        condition: on-failure
        delay: 60s
        max_attempts: 3
        window: 120s
    depends_on:
      - serverconfig
    networks:
      - wiremoney
    environment:
      CONFIG_HOST: configserver:http://serverconfig:8070/


  serverconfig:
    image: jpelegrino/configserver:1.0
    container_name: configserver-ms
    ports:
      - "8070:8070"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - wiremoney


  gatewayserver:
    image: jpelegrino/gatewayserver:1.0
    container_name: gatewayserver-ms
    ports:
      - "8072:8072"
    deploy:
      resources:
        limits:
          memory: 700m
      restart_policy:
        condition: on-failure
        delay: 120s
        max_attempts: 3
        window: 120s
    depends_on:
      - banktranx
      - customers
      - wiretransfer
      - serverconfig
      - eurekaserver
    networks:
      - wiremoney
    environment:
      CONFIG_HOST: configserver:http://serverconfig:8070/
      EUREKA_HOST: http://eurekaserver:8071/eureka/

  banktranx:
    image: jpelegrino/bank:1.0
    container_name: bankservice
    ports:
      - "8093:8093"
    deploy:
      resources:
        limits:
          memory: 700m
      restart_policy:
        condition: on-failure
        delay: 60s
        max_attempts: 3
        window: 120s
    networks:
      - wiremoney
    depends_on:
      - bankdb
      - customers
      - serverconfig
      - eurekaserver
      - rabbit
    environment:
      DB_HOST: bankdb
      DB_PASS: admin
      DB_NAME: bank-db
      CUSTOMER_HOST: http://customers:8000/api/customers/
      CONFIG_HOST: configserver:http://serverconfig:8070/
      EUREKA_HOST: http://eurekaserver:8071/eureka/
      SPRING_PROFILES_ACTIVE: prod
      RABBIT_HOST: rabbit



  customers:
    image: jpelegrino/customers:1.0
    container_name: customerservice
    ports:
      - "8000:8000"
    deploy:
      resources:
        limits:
          memory: 700m
      restart_policy:
        condition: on-failure
        delay: 60s
        max_attempts: 3
        window: 120s
    networks:
      - wiremoney
    depends_on:
      - customerdb
      - serverconfig
      - eurekaserver
    environment:
      DB_HOST: customerdb
      DB_PASS: admin
      DB_NAME: customer-db
      CONFIG_HOST: configserver:http://serverconfig:8070/
      EUREKA_HOST: http://eurekaserver:8071/eureka/
      SPRING_PROFILES_ACTIVE: prod

  messagesms:
    image: jpelegrino/messages:1.0
    container_name: messages-ms
    ports:
      - "9010:9010"
    deploy:
      resources:
        limits:
          memory: 700m
      restart_policy:
        condition: on-failure
        delay: 60s
        max_attempts: 3
        window: 120s
    networks:
      - wiremoney
    depends_on:
      - rabbit
    environment:
      EUREKA_HOST: http://eurekaserver:8071/eureka/
      SPRING_PROFILES_ACTIVE: prod
      RABBIT_HOST: rabbit

  wiretransfer:
    image: jpelegrino/wiretransfer:1.0
    container_name: wiretransfer
    ports:
      - "8001:8001"
    deploy:
      resources:
        limits:
          memory: 700m
      restart_policy:
        condition: on-failure
        delay: 60s
        max_attempts: 3
        window: 120s
    networks:
      - wiremoney
    depends_on:
      - banktranx
      - serverconfig
      - eurekaserver
    environment:
      BANK_HOST: http://banktranx:8093/transactions
      CONFIG_HOST: configserver:http://serverconfig:8070/
      EUREKA_HOST: http://eurekaserver:8071/eureka/
      SPRING_PROFILES_ACTIVE: prod


  customerdb:
    image: mysql:8.0
    container_name: customerdb-serv
    ports:
      - "3362:3306"
    expose:
      - "3362"
    volumes:
      - customerdata:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: customer-db
    networks:
      - wiremoney

  bankdb:
    image: mysql:8.0
    container_name: bank-serv
    ports:
      - "3363:3306"
    expose:
      - "3363"
    volumes:
      - bankdata:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: bank-db
    networks:
      - wiremoney


networks:
  wiremoney:
    driver: "bridge"

volumes:
  customerdata:
  bankdata:
