apiVersion: apps/v1
kind: Deployment
metadata:
  name: gatewayserver-deployment
  labels:
    app: gatewayserver
spec:
  selector:
    matchLabels:
      app: gatewayserver
  template:
    metadata:
      labels:
        app: gatewayserver
    spec:
      containers:
        - name: gatewayserver
          image: jpelegrino/gatewayserver:1.0
          ports:
            - containerPort: 8072
          env:
            - name: CONFIG_HOST
              valueFrom:
                configMapKeyRef:
                  key: CONFIGSERVER_URL
                  name: wiremoney-config

            - name: EUREKA_HOST
              valueFrom:
                configMapKeyRef:
                  key: EURAKASERVER_URL
                  name: wiremoney-config

---
apiVersion: v1
kind: Service
metadata:
  name: gatewayserver-service
  labels:
    app: gatewayserver
spec:
  selector:
    app: gatewayserver
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8072
      targetPort: 8072
