apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitserver-deployment
  labels:
    app: rabbitserver
spec:
  selector:
    matchLabels:
      app: rabbitserver
  template:
    metadata:
      labels:
        app: rabbitserver
    spec:
      containers:
        - name: rabbitserver
          image: rabbitmq:3.12-management
          ports:
            - containerPort: 5672

---
apiVersion: v1
kind: Service
metadata:
  name: rabbitserver-service
  labels:
    app: rabbitserver
spec:
  selector:
    app: rabbitserver
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 5672
      targetPort: 5672
